# Generated by Django 5.0.1 on 2024-01-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='membros_presentes',
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='membros_presentes',
        ),
    ]
