# Generated by Django 5.0.1 on 2024-01-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0002_remove_evento_membros_presentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(choices=[('Inteligência Artificial', 'Inteligência Artificial'), ('Contgramação', 'Contgramação'), ('Finanças Quantitativas', 'Finanças Quantitativas'), ('Desenvolvimento Web', 'Desenvolvimento Web'), ('The Office', 'The Office')], max_length=30),
        ),
    ]
