# Generated by Django 5.0.1 on 2024-01-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0003_alter_grupo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicao',
            name='nome',
            field=models.CharField(choices=[('membro', 'Membro'), ('trainee', 'Trainee'), ('diretor', 'Diretor'), ('lider', 'Líder'), ('vice-presidente', 'Vice-Presidente'), ('presidente', 'Presidente'), ('ex-membro', 'Ex-Membro'), ('fundador', 'Fundador')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posicao',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='area_usuario', to='sistemadev.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='grupo_usuario', to='sistemadev.grupo'),
        ),
        migrations.AddField(
            model_name='user',
            name='posicao',
            field=models.ManyToManyField(blank=True, related_name='posicao_usuario', to='sistemadev.posicao'),
        ),
    ]
