# Generated by Django 5.0.1 on 2024-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0004_alter_posicao_nome_remove_user_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(choices=[('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Projetos', 'Projetos')], max_length=30),
        ),
    ]
