# Generated by Django 5.0.1 on 2024-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0006_area_diretor_grupo_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='dia',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenca',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
