# Generated by Django 5.0.1 on 2024-01-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0007_presenca_dia_presenca_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='justificativa',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
