# Generated by Django 5.0.1 on 2024-01-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0008_alter_presenca_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='justificativa',
        ),
    ]
