# Generated by Django 5.0.1 on 2024-01-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0009_remove_presenca_dia_remove_presenca_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posicao',
        ),
        migrations.AddField(
            model_name='user',
            name='posicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posicao_usuario', to='sistemadev.posicao'),
            preserve_default=False,
        ),
    ]
