# Generated by Django 5.0.1 on 2024-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0011_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
