# Generated by Django 5.0.1 on 2024-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemadev', '0012_user_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
    ]
